name: Publish

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  linting:
    name: Publish to Rubygems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.0"
        bundler-cache: true

    - name: Build the Gem
      run: |
        gem build --strict --output origamindee.gem

    - name: Set credentials
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir ~/.gem
        touch ~/.gem/credentials
        echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
        chmod 600 ~/.gem/credentials

    - name: Publish the Gem
      run: |
        gem push origamindee.gem
