#
# Run unit tests.
#
name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Test ${{ matrix.os }}, Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "macos-latest"
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec rake test
